# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 800)
        MainWindow.setStyleSheet("background-color: rgb(15, 45, 105);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 900, 771))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(15, 45, 105);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(18, 18))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label13 = QtWidgets.QLabel(self.tab)
        self.label13.setGeometry(QtCore.QRect(360, 50, 180, 180))
        self.label13.setPixmap(QtGui.QPixmap("Brain.png"))
        self.label.setGeometry(QtCore.QRect(50, 300, 800, 140))
        font = QtGui.QFont()
        font.setFamily("Padauk")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(70, 200, 109, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("QPushButton{\n"
                                        "  background-color: #137dab;\n"
                                        "  color: #fff;\n}"
                                        )
        self.pushButton.clicked.connect(self.addWinGastro)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 250, 109, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                      "  background-color: #137dab;\n"
                                      "  color: #fff;\n}"
                                      )
        self.pushButton_2.clicked.connect(self.addWinShop)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 350, 109, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                      "  background-color: #137dab;\n"
                                      "  color: #fff;\n}"
                                      )
        self.pushButton_3.clicked.connect(self.addWinAttendance)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 300, 109, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                      "  background-color: #137dab;\n"
                                      "  color: #fff;\n}"
                                      )
        self.pushButton_4.clicked.connect(self.addWinTransport)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 400, 109, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                      "  background-color: #137dab;\n"
                                      "  color: #fff;\n}"
                                      )
        self.pushButton_5.clicked.connect(self.addWinFash)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 150, 109, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                      "  background-color: #137dab;\n"
                                      "  color: #fff;\n}"
                                      )
        self.pushButton_6.clicked.connect(self.addWinTourism)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(280, 350, 480, 25))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(280, 450, 480, 25))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(280, 400, 480, 25))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(280, 500, 480, 25))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(280, 300, 480, 25))
        self.label_8.setObjectName("label_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(70, 450, 109, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setStyleSheet("QPushButton{\n"
                                      "  background-color: #137dab;\n"
                                      "  color: #fff;\n}"
                                      )
        self.pushButton_7.clicked.connect(self.addWinOthers)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 500, 109, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setStyleSheet("QPushButton{\n"
                                      "  background-color: #137dab;\n"
                                      "  color: #fff;\n}"
                                      )
        self.pushButton_8.clicked.connect(self.addWinSpendings)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(280, 250, 340, 25))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(280, 200, 480, 25))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(280, 150, 480, 25))
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 571, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(610, 40, 230, 230))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("hselogo_fullsize_outline.svg"))
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(80, 570, 740, 65))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(23)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(387, 660, 125, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def addWinShop(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Shopping')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10157447 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br>
<br> ID:  10213259 | Age:  43 | Region:  Самарская область | Current Discount:  0 <br>
<br> ID:  10216023 | Age:  20 | Region:  Хабаровский край | Current Discount:  22 <br>
<br> ID:  10216816 | Age:  32 | Region:  Белгородская область | Current Discount:  10 <br>
<br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10218864 | Age:  35 | Region:  г.Санкт-Петербург | Current Discount:  7 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10355392 | Age:  39 | Region:  Республика Башкортостан | Current Discount:  0 <br>
<br> ID:  10355417 | Age:  37 | Region:  г.Москва | Current Discount:  5 <br>
<br> ID:  10355445 | Age:  34 | Region:  Новосибирская область | Current Discount:  8 <br>
<br> ID:  10359664 | Age:  21 | Region:  г.Москва | Current Discount:  21 <br>
<br> ID:  10360759 | Age:  33 | Region:  Иркутская область | Current Discount:  9 <br>
<br> ID:  10361741 | Age:  20 | Region:  Алтайский край | Current Discount:  22 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10404555 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br>
<br> ID:  10550231 | Age:  23 | Region:  Волгоградская область | Current Discount:  19 <br>
<br> ID:  10580277 | Age:  27 | Region:  Московская область | Current Discount:  15 <br>
<br> ID:  10580935 | Age:  34 | Region:  Омская область | Current Discount:  8 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11099056 | Age:  39 | Region:  Псковская область | Current Discount:  0 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11255812 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11257902 | Age:  38 | Region:  Московская область | Current Discount:  0 <br>
<br> ID:  11259088 | Age:  24 | Region:  Хабаровский край | Current Discount:  18 <br>
<br> ID:  11259804 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def addWinTourism(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Tourism')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10220770 | Age:  38 | Region:  Липецкая область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11119835 | Age:  39 | Region:  Ульяновская область | Current Discount:  0 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11257083 | Age:  25 | Region:  г.Санкт-Петербург | Current Discount:  17 <br>
<br> ID:  11257209 | Age:  36 | Region:  Московская область | Current Discount:  6 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11260095 | Age:  26 | Region:  Челябинская область | Current Discount:  16 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def addWinGastro(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Alcohol')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10216816 | Age:  32 | Region:  Белгородская область | Current Discount:  10 <br>
<br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10218209 | Age:  28 | Region:  Томская область | Current Discount:  14 <br>
<br> ID:  10218864 | Age:  35 | Region:  г.Санкт-Петербург | Current Discount:  7 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10355392 | Age:  39 | Region:  Республика Башкортостан | Current Discount:  0 <br>
<br> ID:  10361741 | Age:  20 | Region:  Алтайский край | Current Discount:  22 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10404735 | Age:  34 | Region:  Волгоградская область | Current Discount:  8 <br>
<br> ID:  10574677 | Age:  28 | Region:  Челябинская область | Current Discount:  14 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  11008961 | Age:  34 | Region:  Ростовская область | Current Discount:  8 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11018939 | Age:  34 | Region:  Томская область | Current Discount:  8 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11259088 | Age:  24 | Region:  Хабаровский край | Current Discount:  18 <br>
<br> ID:  11259804 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def addWinTransport(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Transport')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10216816 | Age:  32 | Region:  Белгородская область | Current Discount:  10 <br>
<br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10355417 | Age:  37 | Region:  г.Москва | Current Discount:  5 <br>
<br> ID:  10360759 | Age:  33 | Region:  Иркутская область | Current Discount:  9 <br>
<br> ID:  10361741 | Age:  20 | Region:  Алтайский край | Current Discount:  22 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10404555 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br>
<br> ID:  10404615 | Age:  32 | Region:  Краснодарский край | Current Discount:  10 <br>
<br> ID:  10550231 | Age:  23 | Region:  Волгоградская область | Current Discount:  19 <br>
<br> ID:  10565212 | Age:  38 | Region:  Тамбовская область | Current Discount:  0 <br>
<br> ID:  10574677 | Age:  28 | Region:  Челябинская область | Current Discount:  14 <br>
<br> ID:  10580277 | Age:  27 | Region:  Московская область | Current Discount:  15 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  10838002 | Age:  41 | Region:  Московская область | Current Discount:  0 <br>
<br> ID:  11008961 | Age:  34 | Region:  Ростовская область | Current Discount:  8 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11018939 | Age:  34 | Region:  Томская область | Current Discount:  8 <br>
<br> ID:  11099056 | Age:  39 | Region:  Псковская область | Current Discount:  0 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11257084 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11259088 | Age:  24 | Region:  Хабаровский край | Current Discount:  18 <br>
<br> ID:  11259157 | Age:  41 | Region:  Ростовская область | Current Discount:  0 <br>
<br> ID:  11259804 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def addWinSpendings(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Spendings')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10361741 | Age:  20 | Region:  Алтайский край | Current Discount:  22 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11018939 | Age:  34 | Region:  Томская область | Current Discount:  8 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11259157 | Age:  41 | Region:  Ростовская область | Current Discount:  0 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def addWinFash(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Fashion')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10214653 | Age:  31 | Region:  Челябинская область | Current Discount:  11 <br>
<br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10331702 | Age:  41 | Region:  Тюменская область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10355386 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br>
<br> ID:  10361741 | Age:  20 | Region:  Алтайский край | Current Discount:  22 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10568660 | Age:  38 | Region:  Белгородская область | Current Discount:  0 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11018939 | Age:  34 | Region:  Томская область | Current Discount:  8 <br>
<br> ID:  11124561 | Age:  33 | Region:  г.Санкт-Петербург | Current Discount:  9 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11259157 | Age:  41 | Region:  Ростовская область | Current Discount:  0 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def addWinAttendance(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Attendance')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def addWinOthers(self):
        self.widget = QtWidgets.QWidget()
        self.widget.setWindowTitle('Others')
        self.widget.setGeometry(500, 100, 800, 800)
        self.widget.setStyleSheet("background-color:rgb(15, 45, 105);")
        self.lbl = QtWidgets.QTextBrowser()
        self.lbl.setFontPointSize(20)
        self.lbl.setGeometry(500, 100, 600, 800)
        self.lbl.setHtml("""<span style='font-size:17px; color:white;'><br> ID:  10216816 | Age:  32 | Region:  Белгородская область | Current Discount:  10 <br>
<br> ID:  10217384 | Age:  41 | Region:  Пензенская область | Current Discount:  0 <br>
<br> ID:  10218209 | Age:  28 | Region:  Томская область | Current Discount:  14 <br>
<br> ID:  10218864 | Age:  35 | Region:  г.Санкт-Петербург | Current Discount:  7 <br>
<br> ID:  10219380 | Age:  39 | Region:  Калининградская область | Current Discount:  0 <br>
<br> ID:  10354725 | Age:  37 | Region:  Челябинская область | Current Discount:  5 <br>
<br> ID:  10355392 | Age:  39 | Region:  Республика Башкортостан | Current Discount:  0 <br>
<br> ID:  10361741 | Age:  20 | Region:  Алтайский край | Current Discount:  22 <br>
<br> ID:  10402701 | Age:  34 | Region:  Московская область | Current Discount:  8 <br>
<br> ID:  10404735 | Age:  34 | Region:  Волгоградская область | Current Discount:  8 <br>
<br> ID:  10574677 | Age:  28 | Region:  Челябинская область | Current Discount:  14 <br>
<br> ID:  10583558 | Age:  39 | Region:  Омская область | Current Discount:  0 <br>
<br> ID:  10837991 | Age:  33 | Region:  г.Москва | Current Discount:  9 <br>
<br> ID:  11008961 | Age:  34 | Region:  Ростовская область | Current Discount:  8 <br>
<br> ID:  11011968 | Age:  37 | Region:  Ростовская область | Current Discount:  5 <br>
<br> ID:  11012574 | Age:  32 | Region:  Тюменская область | Current Discount:  10 <br>
<br> ID:  11018939 | Age:  34 | Region:  Томская область | Current Discount:  8 <br>
<br> ID:  11135326 | Age:  38 | Region:  Владимирская область | Current Discount:  0 <br>
<br> ID:  11257217 | Age:  40 | Region:  Красноярский край | Current Discount:  0 <br>
<br> ID:  11259088 | Age:  24 | Region:  Хабаровский край | Current Discount:  18 <br>
<br> ID:  11259804 | Age:  32 | Region:  г.Москва | Current Discount:  10 <br></span>""")
        self.vbox = QtWidgets.QVBoxLayout()
        self.vbox.addWidget(self.lbl)
        self.widget.setLayout(self.vbox)
        self.widget.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Умный Маркетолог"))
        self.label.setText(_translate("MainWindow", "Умный маркетолог -  приложение от бога!"))
        self.label.setStyleSheet('color:white;')
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "About"))
        self.tabWidget.setStyleSheet('color:white;')
        self.pushButton.setText(_translate("MainWindow", "Gastronomic"))
        self.pushButton_2.setText(_translate("MainWindow", "Shopping"))
        self.pushButton_3.setText(_translate("MainWindow", "Attendance"))
        self.pushButton_4.setText(_translate("MainWindow", "Transport"))
        self.pushButton_5.setText(_translate("MainWindow", "Fashion"))
        self.pushButton_6.setText(_translate("MainWindow", "Tourism"))
        self.label_4.setText(_translate("MainWindow", "People with high attendance at different places"))
        self.label_5.setText(_translate("MainWindow", "Unknown transactions customers with good stats"))
        self.label_6.setText(_translate("MainWindow", "Beauty lovers who wants to spend more and more"))
        self.label_7.setText(_translate("MainWindow", "Generally good customers who spend much"))
        self.label_8.setText(_translate("MainWindow", "Active citizens who wants to travel with comfort"))
        self.pushButton_7.setText(_translate("MainWindow", "Other"))
        self.pushButton_8.setText(_translate("MainWindow", "Spendings"))
        self.label_9.setText(_translate("MainWindow", "Shopaholics with money"))
        self.label_10.setText(_translate("MainWindow", "Hungry for food and spending money"))
        self.label_11.setText(_translate("MainWindow", "Travellers or tourists"))
        self.label_12.setText(_translate("MainWindow", "Made By Artur Abgaryan and Millena Cherepanova"))
        self.label_13.setText(_translate("MainWindow", "DSBA-213"))
        self.label_3.setText(_translate("MainWindow", "Which industry are you interested in?"))
        self.label_3.setStyleSheet("color:#ffffff;")
        self.label_4.setStyleSheet("color:#ffffff;")
        self.label_5.setStyleSheet("color:#ffffff;")
        self.label_6.setStyleSheet("color:#ffffff;")
        self.label_7.setStyleSheet("color:#ffffff;")
        self.label_8.setStyleSheet("color:#ffffff;")
        self.label_9.setStyleSheet("color:#ffffff;")
        self.label_10.setStyleSheet("color:#ffffff;")
        self.label_11.setStyleSheet("color:#ffffff;")
        self.label_12.setStyleSheet("color:#ffffff;")
        self.label_13.setStyleSheet("color:#ffffff;")

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
